version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
    rust: "latest"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
